### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ifadardin** [thunlp/TensorFlow-Summarization#13]
```
Traceback (most recent call last):
  File "src/summarization.py", line 241, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/summarization.py", line 229, in main
    decode()
  File "src/summarization.py", line 190, in decode
    data = data_util.load_test_data(FLAGS.test_file, doc_dict)
  File "/Users/ifadardin/Documents/Python/TensorFlow-Summarization-master/script/src/data_util.py", line 181, in load_test_data
    docid, cover = corpus_map2id(docs, doc_dict[0])
TypeError: 'NoneType' object is not subscriptable
```

I keep getting this error message when i run `test.py` i wonder what went wrong?
I use TensorFlow r1.1

**Comment by Hemanth14531** [comment]
Hi did you solve the error?
can you help me?
