### ISSUE TITLE
can't find sum_dict.txt and doc_dict.txt files

### ISSUE THREAD

**Issue by vinayhpandya** [thunlp/TensorFlow-Summarization#8]
i've got the .ckpt files but i cannot find the sum_dict.txt and doc_dict.txt files are they created during training?

**Comment by leopard1** [comment]
Hey, the training script will generate dict files automatically. If you use the same data set, it should be compatible with pre-trained weights. 

Thank you for your question. I will also upload them latter.

**Comment by vinayhpandya** [comment]
Thanks but could you provide me with the files ,it would really help me

**Comment by vinayhpandya** [comment]
i have genrated the dict files but now i am getting an error like


here is the full log

Oct 04 14:15 saver.py[line:1455] INFO Restoring parameters from
model/model.ckpt-300000
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 1039, in _do_call
    return fn(*args)
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 1021, in _run_fn
    status, run_metadata)
  File "C:\Python3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File
"C:\Python3\lib\site-packages\tensorflow\python\framework\errors_impl.py",
line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,23]
= 56047 is not in [0, 30000)
         [[Node: seq2seq/encoder/embedding_lookup =
Gather[Tindices=DT_INT32, Tparams=DT_FLOAT,
_class=["loc:@seq2seq/encoder/embedding"],
validate_indices=true,
_device="/job:localhost/replica:0/task:0/cpu:0"](seq2seq/encoder/embedding/read,
_recv_Placeholder_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/summarization.py", line 241, in <module>
    tf.app.run()
  File "C:\Python3\lib\site-packages\tensorflow\python\platform\app.py",
line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/summarization.py", line 229, in main
    decode()
  File "src/summarization.py", line 214, in decode
    sess, encoder_inputs, encoder_len, geneos=FLAGS.geneos)
  File "C:\Users\vinayp\Desktop\BEP\textsum\src\bigru_model.py", line 227,
in step_beam
    outputs = session.run(output_feed, input_feed)
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 778, in run
    run_metadata_ptr)
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Python3\lib\site-packages\tensorflow\python\client\session.py",
line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,23]
= 56047 is not in [0, 30000)
         [[Node: seq2seq/encoder/embedding_lookup =
Gather[Tindices=DT_INT32, Tparams=DT_FLOAT,
_class=["loc:@seq2seq/encoder/embedding"],
validate_indices=true,
_device="/job:localhost/replica:0/task:0/cpu:0"](seq2seq/encoder/embedding/read,
_recv_Placeholder_0)]]

Caused by op 'seq2seq/encoder/embedding_lookup', defined at:
  File "src/summarization.py", line 241, in <module>
    tf.app.run()
  File "C:\Python3\lib\site-packages\tensorflow\python\platform\app.py",
line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/summarization.py", line 229, in main
    decode()
  File "src/summarization.py", line 196, in decode
    model = create_model(sess, True)
  File "src/summarization.py", line 75, in create_model
    dtype=dtype)
  File "C:\Users\vinayp\Desktop\BEP\textsum\src\bigru_model.py", line 67,
in __init__
    encoder_emb, self.encoder_inputs)
  File
"C:\Python3\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line
119, in embedding_lookup
    params[0], ids, validate_indices=validate_indices, name=name))
  File
"C:\Python3\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line
41, in _do_gather
    params, ids, name=name, validate_indices=validate_indices)
  File
"C:\Python3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line
1207, in gather
    validate_indices=validate_indices, name=name)
  File
"C:\Python3\lib\site-packages\tensorflow\python\framework\op_def_library.py",
line 768, in apply_op
    op_def=op_def)
  File "C:\Python3\lib\site-packages\tensorflow\python\framework\ops.py",
line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Python3\lib\site-packages\tensorflow\python\framework\ops.py",
line 1228, in __init__
    self._traceback = _extract_stack()

here are the screenshots


[image: Inline image 1][image: Inline image 2][image: Inline image 3]
